install:
  - set "PATH=C:\\msys64\\usr\\bin;%PATH%"
  - set "PYTHON27=C:\\Python27\\python.exe"
  - "%PYTHON27% -m pip install -U pip"
build_script:
  - make build
after_build:
  - 7z a -tzip -xr!.* -xr0!build build\\WuLiFang-Nuke-%APPVEYOR_REPO_TAG_NAME%-win.zip
artifacts:
  - path: build\WuLiFang-Nuke-*.zip
    name: Built package
deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_RELEASE_DESCRIPTION)
  provider: GitHub
  auth_token:
    secure: F3Yyeg/9CKfhBQ6baTP5XsOqnquey/5hXl1EtPqmk0WptSzV6STE7M4Pa+BJnTZ2
  artifact: /.*\.zip/
  draft: true
  prerelease: false
  on:
    branch: /v.+/
    APPVEYOR_REPO_TAG: true
